name: Build WLED with PIR Support

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - esp32dev
          - esp32c3dev
          - lolin_s2_mini
          - nodemcuv2
          - esp8266_2m
    
    steps:
    - name: Checkout WLED repository
      uses: actions/checkout@v4
      with:
        repository: Aircoookie/WLED  # Checkout official WLED repo
        ref: '0_15_x'  # Use branch (0_15_x, main) or tag (v0.15.1, v0.14.4)
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Create platformio_override.ini with PIR usermod
      run: |
        cat > platformio_override.ini << 'EOF'
        # PIR Sensor Usermod Build Configuration
        
        [env:esp32dev_pir]
        extends = env:esp32dev
        build_flags = ${env:esp32dev.build_flags}
        custom_usermods = PIR_sensor_switch
        
        [env:esp32c3dev_pir]
        extends = env:esp32c3dev
        build_flags = ${env:esp32c3dev.build_flags}
        custom_usermods = PIR_sensor_switch
        
        [env:lolin_s2_mini_pir]
        extends = env:lolin_s2_mini
        build_flags = ${env:lolin_s2_mini.build_flags}
        custom_usermods = PIR_sensor_switch
        
        [env:nodemcuv2_pir]
        extends = env:nodemcuv2
        build_flags = ${env:nodemcuv2.build_flags}
        custom_usermods = PIR_sensor_switch
        
        [env:esp8266_2m_pir]
        extends = env:esp8266_2m
        build_flags = ${env:esp8266_2m.build_flags}
        custom_usermods = PIR_sensor_switch
        EOF
    
    - name: Build firmware
      run: |
        pio run -e ${{ matrix.environment }}_pir
    
    - name: Rename firmware files
      run: |
        mkdir -p output
        cp .pio/build/${{ matrix.environment }}_pir/firmware.bin output/WLED_${{ matrix.environment }}_PIR.bin || true
        cp .pio/build/${{ matrix.environment }}_pir/firmware.elf output/WLED_${{ matrix.environment }}_PIR.elf || true
    
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WLED-PIR-${{ matrix.environment }}
        path: output/
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: output/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
